# StatefulSet for cartonbot discord bot
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cartonbot
  labels:
    app: cartonbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartonbot
  updateStrategy:
    type: RollingUpdate
  template :
    metadata:
      labels:
        app: cartonbot
    spec:
      serviceAccountName: cartonbot-discord-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
        cloud.google.com/gke-spot: "true"
      tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      terminationGracePeriodSeconds: 25
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "cartonbot"
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: secrets-injector
          image: cartonbot-init-secrets-image
          command:
          - "sh"
          - "-c"
          - "/get-secrets.sh"
          env:
          - name: DISCORD_API_TOKEN_VERSION
            value: "1"
          - name: DISCORD_GUILD_ID_VERSION
            value: "1"
          volumeMounts:
          - name: secrets
            mountPath: "/secrets"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
      containers:
        - name: cartonbot
          image: cartonbot-app-image
          env:
          - name: SECRETS_FILE_PATH
            value: "/app/secrets.yaml"
          volumeMounts:
          - name: secrets
            mountPath: "/app/secrets.yaml"
            readOnly: true
            subPath: "secrets.yaml"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
      volumes:
      - name: secrets
        emptyDir: {}


