name: validate branch

on:  
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - Dockerfile
      - Cargo.toml

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Set ENV Variables"
        run: |
          echo 'RUSTFLAGS="--deny warnings"' >> $GITHUB_ENV
          env
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features