name: Validate Branch

on:  
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - Dockerfile
      - Cargo.toml

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --all-features
        env:
          RUSTFLAGS: --deny warnings
  validate_docker_build:
    name: Validate Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          push: false
