name: validate branch

on:  
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - Dockerfile
      - Cargo.toml

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --all-features
        env:
          RUSTFLAGS: --deny warnings