name: Validate Branch

on:  
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --all-features
        env:
          RUSTFLAGS: --deny warnings
  test-docker-bot:
    uses: pcarton/github-actions/.github/workflows/validate-docker-build.yaml@v0.9.0
    with:
      dockerfile_path: './Dockerfile'
      docker_build_context: '.'
    secrets:
      input_github_token: ${{ secrets.GITHUB_TOKEN }}
  test-docker-secret-injector:
    uses: pcarton/github-actions/.github/workflows/validate-docker-build.yaml@v0.9.0
    with:
      dockerfile_path: './secret-injector/Dockerfile'
      docker_build_context: './secret-injector'
    secrets:
      input_github_token: ${{ secrets.GITHUB_TOKEN }}
