name: make tag

on:
  push:
    branches:
      - master

jobs:
  make-new-release:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      pull-requests: 'read'
      id-token: 'write'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ steps.bump_release.outputs.version }}
    steps:
    - id: bump_release
      name: Bump Release
      uses: rymndhng/release-on-push-action@v0.28.0
      with:
        bump_version_scheme: patch
        dry_run: false
        tag_prefix: 'v'